baseURL = 'https://bjurkovski.github.io/'
languageCode = 'en-us'
title = 'Bruno Jurkovski'
theme = 'typo'

[params]
description = "Hello!"

theme = 'auto'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = ''
homeIntroContent = """
"""

[caches]
  [caches.images]
    dir = ':cacheDir/images'
